<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_choice</name>
   <tag></tag>
   <elementGuidId>e017ad75-1020-4506-a1e2-d6236dc8d7bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='page_body']/descendant::div[@class='choices'][${rowNo}]//div[${choice}]//div[1]//label[1]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='page_body']/descendant::div[@class='choices'][${rowNo}]//div[${choice}]//div[1]//label[1]//label[1]</value>
   </webElementProperties>
</WebElementEntity>
